definitions:
  models.LoginModel:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.UserModel:
    properties:
      email:
        type: string
      fullname:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /getProfile:
    get:
      consumes:
      - application/json
      description: login endpoint
      parameters:
      - description: data search by fullname
        in: query
        name: fullname
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - Profile
  /login:
    post:
      consumes:
      - application/json
      description: login endpoint
      parameters:
      - description: PARAM
        in: body
        name: parameter
        required: true
        schema:
          $ref: '#/definitions/models.LoginModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: login endpoint
      parameters:
      - description: PARAM
        in: body
        name: parameter
        required: true
        schema:
          $ref: '#/definitions/models.UserModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - Auth
swagger: "2.0"
